//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TipBot_BL.FantasyPortfolio
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FantasyPortfolio_DBEntities : DbContext
    {
        public FantasyPortfolio_DBEntities()
            : base("name=FantasyPortfolio_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Coin> Coins { get; set; }
        public virtual DbSet<Portfolio> Portfolios { get; set; }
        public virtual DbSet<Round> Rounds { get; set; }
        public virtual DbSet<Leaderboard> Leaderboards { get; set; }
        public virtual DbSet<LeaderboardTicker> LeaderboardTickers { get; set; }
        public virtual DbSet<FlipResults> FlipResults { get; set; }
        public virtual DbSet<FlipLeaderboard> FlipLeaderboard { get; set; }
        public virtual DbSet<FlipResultStatistics> FlipResultStatistics { get; set; }
    }
}
