//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TipBot_BL.FantasyPortfolio
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlipLeaderboard
    {
        public long ID { get; set; }
        public string UserId { get; set; }
        public Nullable<decimal> TotalBet { get; set; }
        public Nullable<int> TotalWins { get; set; }
    }
}
