//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TipBot_BL.FantasyPortfolio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leaderboard
    {
        public Nullable<long> RN { get; set; }
        public int RoundId { get; set; }
        public string UserId { get; set; }
        public Nullable<decimal> totalamount { get; set; }
    }
}
