//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TipBot_BL.FantasyPortfolio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Portfolio
    {
        public int Id { get; set; }
        public int RoundId { get; set; }
        public string UserId { get; set; }
        public int TickerId { get; set; }
        public decimal CoinAmount { get; set; }
    
        public virtual Round Round { get; set; }
    }
}
