//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TipBot_BL.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NDc5NTY2MzUyODEwNzcwNDcy.DlbGnA.L86bC8uwRabPzqVifmEax4bFA3U")]
        public string DiscordToken {
            get {
                return ((string)(this["DiscordToken"]));
            }
            set {
                this["DiscordToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("458146332029353996")]
        public ulong PriceCheckChannel {
            get {
                return ((ulong)(this["PriceCheckChannel"]));
            }
            set {
                this["PriceCheckChannel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("460734356919681024")]
        public ulong TipBotChannel {
            get {
                return ((ulong)(this["TipBotChannel"]));
            }
            set {
                this["TipBotChannel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("486492693787312129")]
        public ulong FantasyChannel {
            get {
                return ((ulong)(this["FantasyChannel"]));
            }
            set {
                this["FantasyChannel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("456496645371199500")]
        public ulong GuildId {
            get {
                return ((ulong)(this["GuildId"]));
            }
            set {
                this["GuildId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://127.0.0.1:6533")]
        public string QT_IP {
            get {
                return ((string)(this["QT_IP"]));
            }
            set {
                this["QT_IP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("yokomoko")]
        public string QT_Username {
            get {
                return ((string)(this["QT_Username"]));
            }
            set {
                this["QT_Username"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("584256")]
        public string QT_Password {
            get {
                return ((string)(this["QT_Password"]));
            }
            set {
                this["QT_Password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MYNT")]
        public string BaseCurrency {
            get {
                return ((string)(this["BaseCurrency"]));
            }
            set {
                this["BaseCurrency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://chain.myntcurrency.org/tx/")]
        public string ExplorerPrefix {
            get {
                return ((string)(this["ExplorerPrefix"]));
            }
            set {
                this["ExplorerPrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExplorerSuffix {
            get {
                return ((string)(this["ExplorerSuffix"]));
            }
            set {
                this["ExplorerSuffix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("109568")]
        public string Setting {
            get {
                return ((string)(this["Setting"]));
            }
            set {
                this["Setting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Help support the developer funds, by donating or mining to MVT2AJDK7CYTtWo5fX9u48" +
            "eQT5ynWPyFFd")]
        public string FooterText {
            get {
                return ((string)(this["FooterText"]));
            }
            set {
                this["FooterText"] = value;
            }
        }
    }
}
